#!/usr/bin/env python3
"""
Generate Perseus-compatible TEI XML for an aligned English translation.

Produces:
  <output_dir>/<cts_work_id>.perseus-eng80.xml
  <output_dir>/__cts__eng80_fragment.xml

The English text is structured with CTS-compatible divs and milestone
markers linking to the source language CTS references.
"""

import json
import sys
from pathlib import Path
from lxml import etree

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

TEI_NS = "http://www.tei-c.org/ns/1.0"
XML_NS = "http://www.w3.org/XML/1998/namespace"
NSMAP = {None: TEI_NS}


def load_config(work_name):
    config_path = PROJECT_ROOT / "scripts" / "works" / work_name / "config.json"
    with open(config_path) as f:
        return json.load(f)


def main(work_name):
    config = load_config(work_name)
    out_dir = PROJECT_ROOT / config["output_dir"]

    align_path = out_dir / "entity_validated_alignments.json"
    english_path = out_dir / "english_sections.json"

    for p in [align_path, english_path]:
        if not p.exists():
            print(f"Error: {p} not found")
            raise SystemExit(1)

    with open(align_path) as f:
        alignments = json.load(f)
    with open(english_path) as f:
        english_data = json.load(f)

    if isinstance(english_data, list):
        english_data = {"sections": english_data}

    name = config["name"]

    # Build CTS work ID from config
    gr_source = config.get("greek_source", {})
    tlg_id = gr_source.get("tlg_id", "")
    work_id = gr_source.get("work_id", "")
    work_ids = gr_source.get("work_ids", [work_id] if work_id else [])

    en_source = config.get("english_source", {})
    translator = en_source.get("translator", "Unknown")
    en_date = en_source.get("date", "")
    author = config.get("author", "")
    work_title = config.get("work_title", "")

    for wid in work_ids:
        cts_work = f"{tlg_id}.{wid}"
        urn = f"urn:cts:greekLit:{cts_work}.perseus-eng80"

        out_tei = out_dir / f"{cts_work}.perseus-eng80.xml"

        print(f"Generating Perseus TEI: {out_tei.name}")

        # Build TEI document
        tei = etree.Element(f"{{{TEI_NS}}}TEI", nsmap=NSMAP)

        # Header
        header = etree.SubElement(tei, f"{{{TEI_NS}}}teiHeader")
        file_desc = etree.SubElement(header, f"{{{TEI_NS}}}fileDesc")

        title_stmt = etree.SubElement(file_desc, f"{{{TEI_NS}}}titleStmt")
        title_el = etree.SubElement(title_stmt, f"{{{TEI_NS}}}title")
        title_el.text = f"{author}, {work_title}"
        author_el = etree.SubElement(title_stmt, f"{{{TEI_NS}}}author")
        author_el.text = author
        editor_el = etree.SubElement(title_stmt, f"{{{TEI_NS}}}editor")
        editor_el.set("role", "translator")
        editor_el.text = translator

        pub_stmt = etree.SubElement(file_desc, f"{{{TEI_NS}}}publicationStmt")
        pub_p = etree.SubElement(pub_stmt, f"{{{TEI_NS}}}p")
        pub_p.text = "Generated by Diodorus alignment pipeline."

        source_desc = etree.SubElement(file_desc, f"{{{TEI_NS}}}sourceDesc")
        bibl = etree.SubElement(source_desc, f"{{{TEI_NS}}}bibl")
        bibl.text = f"{translator} ({en_date}). Public domain."

        # Encoding desc with CTS refsDecl
        enc_desc = etree.SubElement(header, f"{{{TEI_NS}}}encodingDesc")
        refs_decl = etree.SubElement(enc_desc, f"{{{TEI_NS}}}refsDecl")
        refs_decl.set("n", "CTS")

        cref = etree.SubElement(refs_decl, f"{{{TEI_NS}}}cRefPattern")
        cref.set("n", "section")
        cref.set("matchPattern", r"(\w+)\.(\w+)")
        cref.set("replacementPattern",
                 "#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:p[@n='$2'])")

        # Text body
        text_el = etree.SubElement(tei, f"{{{TEI_NS}}}text")
        body = etree.SubElement(text_el, f"{{{TEI_NS}}}body")

        trans_div = etree.SubElement(body, f"{{{TEI_NS}}}div")
        trans_div.set("type", "translation")
        trans_div.set(f"{{{XML_NS}}}lang", "eng")
        trans_div.set("n", urn)

        # Group English sections by book
        from collections import defaultdict
        en_by_book = defaultdict(list)
        for s in english_data["sections"]:
            # Only include sections from this work (for multi-work configs)
            s_work = s.get("work", "")
            if work_ids and len(work_ids) > 1:
                # Multi-work: match by work name or work_id
                # For Iamblichus: work_ids = ["tlg001", "tlg006"]
                # sections have work = "De Vita Pythagorica" or "De Mysteriis"
                # We need to map work_id to work name — skip if not matching
                pass  # TODO: filter for multi-work
            en_by_book[s["book"]].append(s)

        # Build alignment lookup: english cts_ref -> greek cts_ref
        en_to_gr = {}
        for a in alignments:
            en_ref = a.get("english_cts_ref", a.get("english_section", ""))
            gr_ref = a.get("greek_cts_ref")
            if en_ref and gr_ref:
                en_to_gr[str(en_ref)] = gr_ref

        for book_key in sorted(en_by_book.keys(),
                                key=lambda x: int(x) if x.isdigit() else x):
            book_secs = en_by_book[book_key]

            book_div = etree.SubElement(trans_div, f"{{{TEI_NS}}}div")
            book_div.set("type", "textpart")
            book_div.set("subtype", "book")
            book_div.set("n", str(book_key))

            for s in book_secs:
                sec_n = s.get("section", s.get("cts_ref", ""))

                # Add milestone for Greek reference if aligned
                gr_ref = en_to_gr.get(str(s.get("cts_ref", "")))
                if gr_ref:
                    ms = etree.SubElement(book_div, f"{{{TEI_NS}}}milestone")
                    ms.set("unit", "section")
                    ms.set("n", str(gr_ref))

                p = etree.SubElement(book_div, f"{{{TEI_NS}}}p")
                p.set("n", str(sec_n))
                p.text = s["text"]

        # Write
        tree = etree.ElementTree(tei)
        with open(out_tei, "wb") as f:
            f.write(b'<?xml version="1.0" encoding="UTF-8"?>\n')
            tree.write(f, encoding="UTF-8", xml_declaration=False, pretty_print=True)

        # Verify well-formed
        etree.parse(str(out_tei))
        print(f"  Written and validated: {out_tei.name}")

    # CTS catalog fragment — named per work to avoid collisions
    out_cts = out_dir / f"__cts__eng80_{name}.xml"
    cts_lines = ['<?xml version="1.0" encoding="UTF-8"?>']
    cts_lines.append(f'<!-- CTS catalog entry for {author} {work_title} English translation -->')
    for wid in work_ids:
        cts_work = f"{tlg_id}.{wid}"
        urn = f"urn:cts:greekLit:{cts_work}.perseus-eng80"
        cts_lines.append(
            f'<ti:translation xmlns:ti="http://chs.harvard.edu/xmlns/cts" '
            f'urn="{urn}" workUrn="urn:cts:greekLit:{cts_work}" xml:lang="eng">'
        )
        cts_lines.append(f'  <ti:label xml:lang="eng">{translator} ({en_date})</ti:label>')
        cts_lines.append(f'  <ti:description xml:lang="eng">{translator} translation of '
                         f'{author}, {work_title}. Public domain.</ti:description>')
        cts_lines.append('</ti:translation>')

    with open(out_cts, "w", encoding="utf-8") as f:
        f.write("\n".join(cts_lines) + "\n")

    print(f"  Written: {out_cts.name}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/pipeline/generate_perseus_tei.py <work_name>")
        sys.exit(1)
    main(sys.argv[1])
